# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_no', models.IntegerField()),
                ('catalog_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
