# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 08:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20180201_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2018, 2, 1, 8, 34, 35, 763554, tzinfo=utc)),
        ),
    ]
