# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 07:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20180205_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_no',
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2018, 2, 5, 7, 42, 51, 630898, tzinfo=utc)),
        ),
    ]
