# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20180205_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.CharField(max_length=20),
        ),
    ]
