# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_auto_20180205_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(null=True),
        ),
    ]
