# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_auto_20180205_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='catalog_no',
        ),
        migrations.AlterField(
            model_name='book',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Catalog'),
        ),
    ]
