# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-05 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_auto_20180301_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='catalog',
            field=models.CharField(max_length=25),
        ),
    ]
