# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-05 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_auto_20180305_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_translator',
            new_name='translator',
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='catalog_name',
            new_name='catalog',
        ),
    ]
