# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-07 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_auto_20180305_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='photo_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
