# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-07 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_book_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='catalog',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='book',
            name='photo_url',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
