# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-07 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_auto_20180307_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='catalog',
            field=models.CharField(max_length=25),
        ),
    ]
