# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-07 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0022_auto_20180307_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='catalog_photo',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
