# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-10 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0024_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book', verbose_name='書名'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.TextField(blank=True, max_length=200, verbose_name='給個留言'),
        ),
    ]
