# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-13 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0026_auto_20180312_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='catalog_photo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='rating',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book', verbose_name='書名'),
        ),
    ]
