# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-16 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0032_auto_20180316_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='likes',
        ),
        migrations.AlterField(
            model_name='book',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='rating',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book', verbose_name='書名'),
        ),
    ]
