# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-26 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0056_auto_20180414_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book', verbose_name='書名'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('女', '女'), ('男', '男'), ('不想回答', '不想回答')], default='女', max_length=1, verbose_name='性別'),
        ),
    ]
