"""
Django settings for book_sites project.

Generated by 'django-admin startproject' using Django 1.11.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'hk3-y(u+p=09fi4=wc)y$du&&vw3szitwyv+whow^7*4#xefru'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  #False: css、模板等等無法載入???????????????????????????????????????

ALLOWED_HOSTS = []
#ALLOWED_HOSTS = ['163.18.42.178']

# Application definition

INSTALLED_APPS = [
	'import_export',
	#'grappelli',
	'django.contrib.sites',
	#http://django-registration-redux.readthedocs.io/en/latest/quickstart.html
	'registration', #should be immediately above 'django.contrib.admin'
	'django.contrib.admin',
	'django.contrib.auth',
	
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'book',
	
]



MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'django.middleware.common.BrokenLinkEmailsMiddleware',

]

ROOT_URLCONF = 'book_sites.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [os.path.join(BASE_DIR, 'templates')],#.replace('\\', '/'),
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
				'django.template.context_processors.media'
			],
		},
	},
]


WSGI_APPLICATION = 'book_sites.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.sqlite3',
		'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
	}
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]



# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'zh-hant'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'book/media')

STATICFILES_DIRS = [
	os.path.join(BASE_DIR, "static"),
	#'/var/www/static/',
]


IMPORT_EXPORT_USE_TRANSACTIONS = True 

LOGIN_URL = '/accounts/login/' # 預設 login page 的 url
LOGIN_REDIRECT_URL = '/'  #最前面一定要有 /
#LOGOUT_REDIRECT_URL = '/' # logout 完之後導向的頁面

#Django Registration redux settings
REGISTRATION_OPEN = True
ACCOUNT_ACTIVATION_DAYS = 2 #帳號cookie存活時間 
REGISTRATION_AUTO_LOGIN = True # 註冊帳號之後 自動login

SITE_ID = 1

#Add "email" ability to your app
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'testing@example.com'
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_USE_TLS = False
EMAIL_PORT = 1025